%% Generated by the Erlang ASN.1 compiler. Version: 5.4.2
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module PEDefinitions.

-ifndef(_PROFILE_HRL_).
-define(_PROFILE_HRL_, true).

-record('PEHeader', {
  mandated = asn1_NOVALUE,
  identification
  %% with extension mark
}).

-record('PE-Dummy', {
}).

-record('ProfileHeader', {
  'major-version',
  'minor-version',
  profileType = asn1_NOVALUE,
  iccid,
  pol = asn1_NOVALUE,
  'eUICC-Mandatory-services',
  'eUICC-Mandatory-GFSTEList',
  connectivityParameters = asn1_NOVALUE,
  'eUICC-Mandatory-AIDs' = asn1_NOVALUE,
  iotOptions = asn1_NOVALUE
  %% with extension mark
}).

-record('ProfileHeader_eUICC-Mandatory-AIDs_SEQOF', {
  aid,
  version
  %% with extension mark
}).

-record('IotOptions', {
  pix
  %% with extension mark
}).

-record('ServicesList', {
  contactless = asn1_NOVALUE,
  usim = asn1_NOVALUE,
  isim = asn1_NOVALUE,
  csim = asn1_NOVALUE,
  milenage = asn1_NOVALUE,
  tuak128 = asn1_NOVALUE,
  cave = asn1_NOVALUE,
  'gba-usim' = asn1_NOVALUE,
  'gba-isim' = asn1_NOVALUE,
  mbms = asn1_NOVALUE,
  eap = asn1_NOVALUE,
  javacard = asn1_NOVALUE,
  multos = asn1_NOVALUE,
  'multiple-usim' = asn1_NOVALUE,
  'multiple-isim' = asn1_NOVALUE,
  'multiple-csim' = asn1_NOVALUE,
  tuak256 = asn1_NOVALUE,
  'usim-test-algorithm' = asn1_NOVALUE,
  'ber-tlv' = asn1_NOVALUE,
  dfLink = asn1_NOVALUE,
  'cat-tp' = asn1_NOVALUE,
  'get-identity' = asn1_NOVALUE,
  'profile-a-x25519' = asn1_NOVALUE,
  'profile-b-p256' = asn1_NOVALUE,
  suciCalculatorApi = asn1_NOVALUE,
  'dns-resolution' = asn1_NOVALUE,
  scp11ac = asn1_NOVALUE,
  'scp11c-authorization-mechanism' = asn1_NOVALUE,
  s16mode = asn1_NOVALUE,
  eaka = asn1_NOVALUE
  %% with extension mark
}).

-record('ProprietaryInfo', {
  specialFileInformation = asn1_DEFAULT,
  fillPattern = asn1_NOVALUE,
  repeatPattern = asn1_NOVALUE,
  maximumFileSize = asn1_NOVALUE,
  fileDetails = asn1_DEFAULT
  %% with extension mark
}).

-record('Fcp', {
  fileDescriptor = asn1_NOVALUE,
  fileID = asn1_NOVALUE,
  dfName = asn1_NOVALUE,
  lcsi = asn1_DEFAULT,
  securityAttributesReferenced = asn1_NOVALUE,
  efFileSize = asn1_NOVALUE,
  pinStatusTemplateDO = asn1_NOVALUE,
  shortEFID = asn1_NOVALUE,
  proprietaryEFInfo = asn1_NOVALUE,
  linkPath = asn1_NOVALUE
  %% with extension mark
}).

-record('PE-MF', {
  'mf-header',
  templateID,
  mf,
  'ef-pl' = asn1_NOVALUE,
  'ef-iccid',
  'ef-dir',
  'ef-arr',
  'ef-umpc' = asn1_NOVALUE
  %% with extension mark
}).

-record('PE-CD', {
  'cd-header',
  templateID,
  'df-cd',
  'ef-launchpad' = asn1_NOVALUE,
  'ef-icon' = asn1_NOVALUE
  %% with extension mark
}).

-record('PE-TELECOM', {
  'telecom-header',
  templateID,
  'df-telecom',
  'ef-arr' = asn1_NOVALUE,
  'ef-rma' = asn1_NOVALUE,
  'ef-sume' = asn1_NOVALUE,
  'ef-ice-dn' = asn1_NOVALUE,
  'ef-ice-ff' = asn1_NOVALUE,
  'ef-psismsc' = asn1_NOVALUE,
  'df-graphics' = asn1_NOVALUE,
  'ef-img' = asn1_NOVALUE,
  'ef-iidf' = asn1_NOVALUE,
  'ef-ice-graphics' = asn1_NOVALUE,
  'ef-launch-scws' = asn1_NOVALUE,
  'ef-icon' = asn1_NOVALUE,
  'df-phonebook' = asn1_NOVALUE,
  'ef-pbr' = asn1_NOVALUE,
  'ef-ext1' = asn1_NOVALUE,
  'ef-aas' = asn1_NOVALUE,
  'ef-gas' = asn1_NOVALUE,
  'ef-psc' = asn1_NOVALUE,
  'ef-cc' = asn1_NOVALUE,
  'ef-puid' = asn1_NOVALUE,
  'ef-iap' = asn1_NOVALUE,
  'ef-adn' = asn1_NOVALUE,
  'ef-pbc' = asn1_NOVALUE,
  'ef-anr' = asn1_NOVALUE,
  'ef-puri' = asn1_NOVALUE,
  'ef-email' = asn1_NOVALUE,
  'ef-sne' = asn1_NOVALUE,
  'ef-uid' = asn1_NOVALUE,
  'ef-grp' = asn1_NOVALUE,
  'ef-ccp1' = asn1_NOVALUE,
  'df-multimedia' = asn1_NOVALUE,
  'ef-mml' = asn1_NOVALUE,
  'ef-mmdf' = asn1_NOVALUE,
  'df-mmss' = asn1_NOVALUE,
  'ef-mlpl' = asn1_NOVALUE,
  'ef-mspl' = asn1_NOVALUE,
  'ef-mmssmode' = asn1_NOVALUE,
  'df-mcs' = asn1_NOVALUE,
  'ef-mst' = asn1_NOVALUE,
  'ef-mcs-config' = asn1_NOVALUE,
  'df-v2x' = asn1_NOVALUE,
  'ef-vst' = asn1_NOVALUE,
  'ef-v2x-config' = asn1_NOVALUE,
  'ef-v2xp-pc5' = asn1_NOVALUE,
  'ef-v2xp-Uu' = asn1_NOVALUE
  %% with extension mark
}).

-record('PE-USIM', {
  'usim-header',
  templateID,
  'adf-usim',
  'ef-imsi',
  'ef-arr',
  'ef-keys' = asn1_NOVALUE,
  'ef-keysPS' = asn1_NOVALUE,
  'ef-hpplmn' = asn1_NOVALUE,
  'ef-ust',
  'ef-fdn' = asn1_NOVALUE,
  'ef-sms' = asn1_NOVALUE,
  'ef-smsp' = asn1_NOVALUE,
  'ef-smss' = asn1_NOVALUE,
  'ef-spn',
  'ef-est',
  'ef-start-hfn' = asn1_NOVALUE,
  'ef-threshold' = asn1_NOVALUE,
  'ef-psloci' = asn1_NOVALUE,
  'ef-acc',
  'ef-fplmn' = asn1_NOVALUE,
  'ef-loci' = asn1_NOVALUE,
  'ef-ad' = asn1_NOVALUE,
  'ef-ecc',
  'ef-netpar' = asn1_NOVALUE,
  'ef-epsloci' = asn1_NOVALUE,
  'ef-epsnsc' = asn1_NOVALUE
  %% with extension mark
}).

-record('PE-OPT-USIM', {
  'optusim-header',
  templateID,
  'ef-li' = asn1_NOVALUE,
  'ef-acmax' = asn1_NOVALUE,
  'ef-acm' = asn1_NOVALUE,
  'ef-gid1' = asn1_NOVALUE,
  'ef-gid2' = asn1_NOVALUE,
  'ef-msisdn' = asn1_NOVALUE,
  'ef-puct' = asn1_NOVALUE,
  'ef-cbmi' = asn1_NOVALUE,
  'ef-cbmid' = asn1_NOVALUE,
  'ef-sdn' = asn1_NOVALUE,
  'ef-ext2' = asn1_NOVALUE,
  'ef-ext3' = asn1_NOVALUE,
  'ef-cbmir' = asn1_NOVALUE,
  'ef-plmnwact' = asn1_NOVALUE,
  'ef-oplmnwact' = asn1_NOVALUE,
  'ef-hplmnwact' = asn1_NOVALUE,
  'ef-dck' = asn1_NOVALUE,
  'ef-cnl' = asn1_NOVALUE,
  'ef-smsr' = asn1_NOVALUE,
  'ef-bdn' = asn1_NOVALUE,
  'ef-ext5' = asn1_NOVALUE,
  'ef-ccp2' = asn1_NOVALUE,
  'ef-ext4' = asn1_NOVALUE,
  'ef-acl' = asn1_NOVALUE,
  'ef-cmi' = asn1_NOVALUE,
  'ef-ici' = asn1_NOVALUE,
  'ef-oci' = asn1_NOVALUE,
  'ef-ict' = asn1_NOVALUE,
  'ef-oct' = asn1_NOVALUE,
  'ef-vgcs' = asn1_NOVALUE,
  'ef-vgcss' = asn1_NOVALUE,
  'ef-vbs' = asn1_NOVALUE,
  'ef-vbss' = asn1_NOVALUE,
  'ef-emlpp' = asn1_NOVALUE,
  'ef-aaem' = asn1_NOVALUE,
  'ef-hiddenkey' = asn1_NOVALUE,
  'ef-pnn' = asn1_NOVALUE,
  'ef-opl' = asn1_NOVALUE,
  'ef-mbdn' = asn1_NOVALUE,
  'ef-ext6' = asn1_NOVALUE,
  'ef-mbi' = asn1_NOVALUE,
  'ef-mwis' = asn1_NOVALUE,
  'ef-cfis' = asn1_NOVALUE,
  'ef-ext7' = asn1_NOVALUE,
  'ef-spdi' = asn1_NOVALUE,
  'ef-mmsn' = asn1_NOVALUE,
  'ef-ext8' = asn1_NOVALUE,
  'ef-mmsicp' = asn1_NOVALUE,
  'ef-mmsup' = asn1_NOVALUE,
  'ef-mmsucp' = asn1_NOVALUE,
  'ef-nia' = asn1_NOVALUE,
  'ef-vgcsca' = asn1_NOVALUE,
  'ef-vbsca' = asn1_NOVALUE,
  'ef-gbabp' = asn1_NOVALUE,
  'ef-msk' = asn1_NOVALUE,
  'ef-muk' = asn1_NOVALUE,
  'ef-ehplmn' = asn1_NOVALUE,
  'ef-gbanl' = asn1_NOVALUE,
  'ef-ehplmnpi' = asn1_NOVALUE,
  'ef-lrplmnsi' = asn1_NOVALUE,
  'ef-nafkca' = asn1_NOVALUE,
  'ef-spni' = asn1_NOVALUE,
  'ef-pnni' = asn1_NOVALUE,
  'ef-ncp-ip' = asn1_NOVALUE,
  'ef-ufc' = asn1_NOVALUE,
  'ef-nasconfig' = asn1_NOVALUE,
  'ef-uicciari' = asn1_NOVALUE,
  'ef-pws' = asn1_NOVALUE,
  'ef-fdnuri' = asn1_NOVALUE,
  'ef-bdnuri' = asn1_NOVALUE,
  'ef-sdnuri' = asn1_NOVALUE,
  'ef-ial' = asn1_NOVALUE,
  'ef-ips' = asn1_NOVALUE,
  'ef-ipd' = asn1_NOVALUE,
  'ef-epdgid' = asn1_NOVALUE,
  'ef-epdgselection' = asn1_NOVALUE,
  'ef-epdgidem' = asn1_NOVALUE,
  'ef-epdgselectionem' = asn1_NOVALUE,
  'ef-frompreferred' = asn1_NOVALUE,
  'ef-imsconfigdata' = asn1_NOVALUE,
  'ef-3gpppsdataoff' = asn1_NOVALUE,
  'ef-3gpppsdataoffservicelist' = asn1_NOVALUE,
  'ef-xcapconfigdata' = asn1_NOVALUE,
  'ef-earfcnlist' = asn1_NOVALUE,
  'ef-mudmidconfigdata' = asn1_NOVALUE,
  'ef-eaka' = asn1_NOVALUE
  %% with extension mark
}).

-record('PE-PHONEBOOK', {
  'phonebook-header',
  templateID,
  'df-phonebook',
  'ef-pbr' = asn1_NOVALUE,
  'ef-ext1' = asn1_NOVALUE,
  'ef-aas' = asn1_NOVALUE,
  'ef-gas' = asn1_NOVALUE,
  'ef-psc' = asn1_NOVALUE,
  'ef-cc' = asn1_NOVALUE,
  'ef-puid' = asn1_NOVALUE,
  'ef-iap' = asn1_NOVALUE,
  'ef-adn' = asn1_NOVALUE,
  'ef-pbc' = asn1_NOVALUE,
  'ef-anr' = asn1_NOVALUE,
  'ef-puri' = asn1_NOVALUE,
  'ef-email' = asn1_NOVALUE,
  'ef-sne' = asn1_NOVALUE,
  'ef-uid' = asn1_NOVALUE,
  'ef-grp' = asn1_NOVALUE,
  'ef-ccp1' = asn1_NOVALUE
  %% with extension mark
}).

-record('PE-GSM-ACCESS', {
  'gsm-access-header',
  templateID,
  'df-gsm-access',
  'ef-kc' = asn1_NOVALUE,
  'ef-kcgprs' = asn1_NOVALUE,
  'ef-cpbcch' = asn1_NOVALUE,
  'ef-invscan' = asn1_NOVALUE
  %% with extension mark
}).

-record('PE-DF-5GS', {
  'df-5gs-header',
  templateID,
  'df-df-5gs',
  'ef-5gs3gpploci' = asn1_NOVALUE,
  'ef-5gsn3gpploci' = asn1_NOVALUE,
  'ef-5gs3gppnsc' = asn1_NOVALUE,
  'ef-5gsn3gppnsc' = asn1_NOVALUE,
  'ef-5gauthkeys' = asn1_NOVALUE,
  'ef-uac-aic' = asn1_NOVALUE,
  'ef-suci-calc-info' = asn1_NOVALUE,
  'ef-opl5g' = asn1_NOVALUE,
  'ef-supinai' = asn1_NOVALUE,
  'ef-routing-indicator' = asn1_NOVALUE,
  'ef-ursp' = asn1_NOVALUE,
  'ef-tn3gppsnn' = asn1_NOVALUE,
  'ef-cag' = asn1_NOVALUE,
  'ef-sor-cmci' = asn1_NOVALUE,
  'ef-dri' = asn1_NOVALUE,
  'ef-5gsedrx' = asn1_NOVALUE,
  'ef-5gnswo-conf' = asn1_NOVALUE,
  'ef-mchpplmn' = asn1_NOVALUE,
  'ef-kausf-derivation' = asn1_NOVALUE
  %% with extension mark
}).

-record('PE-DF-SAIP', {
  'df-saip-header',
  templateID,
  'df-df-saip',
  'ef-suci-calc-info-usim' = asn1_NOVALUE
  %% with extension mark
}).

-record('PE-DF-SNPN', {
  'df-snpn-header',
  templateID,
  'df-df-snpn',
  'ef-pws-snpn' = asn1_NOVALUE
  %% with extension mark
}).

-record('PE-DF-5GPROSE', {
  'df-5g-prose-header',
  templateID,
  'df-df-5g-prose',
  'ef-5g-prose-st' = asn1_NOVALUE,
  'ef-5g-prose-dd' = asn1_NOVALUE,
  'ef-5g-prose-dc' = asn1_NOVALUE,
  'ef-5g-prose-u2nru' = asn1_NOVALUE,
  'ef-5g-prose-ru' = asn1_NOVALUE,
  'ef-5g-prose-uir' = asn1_NOVALUE
  %% with extension mark
}).

-record('PE-ISIM', {
  'isim-header',
  templateID,
  'adf-isim',
  'ef-impi',
  'ef-impu',
  'ef-domain',
  'ef-ist',
  'ef-ad' = asn1_NOVALUE,
  'ef-arr'
  %% with extension mark
}).

-record('PE-OPT-ISIM', {
  'optisim-header',
  templateID,
  'ef-pcscf' = asn1_NOVALUE,
  'ef-sms' = asn1_NOVALUE,
  'ef-smsp' = asn1_NOVALUE,
  'ef-smss' = asn1_NOVALUE,
  'ef-smsr' = asn1_NOVALUE,
  'ef-gbabp' = asn1_NOVALUE,
  'ef-gbanl' = asn1_NOVALUE,
  'ef-nafkca' = asn1_NOVALUE,
  'ef-uicciari' = asn1_NOVALUE,
  'ef-frompreferred' = asn1_NOVALUE,
  'ef-imsconfigdata' = asn1_NOVALUE,
  'ef-xcapconfigdata' = asn1_NOVALUE,
  'ef-webrtcuri' = asn1_NOVALUE,
  'ef-mudmidconfigdata' = asn1_NOVALUE
  %% with extension mark
}).

-record('PE-CSIM', {
  'csim-header',
  templateID,
  'adf-csim',
  'ef-arr',
  'ef-call-count',
  'ef-imsi-m',
  'ef-imsi-t',
  'ef-tmsi',
  'ef-ah',
  'ef-aop',
  'ef-aloc',
  'ef-cdmahome',
  'ef-znregi',
  'ef-snregi',
  'ef-distregi',
  'ef-accolc',
  'ef-term',
  'ef-acp',
  'ef-prl',
  'ef-ruimid',
  'ef-csim-st',
  'ef-spc',
  'ef-otapaspc',
  'ef-namlock',
  'ef-ota',
  'ef-sp',
  'ef-esn-meid-me',
  'ef-li',
  'ef-usgind',
  'ef-ad',
  'ef-max-prl',
  'ef-spcs',
  'ef-mecrp',
  'ef-home-tag',
  'ef-group-tag',
  'ef-specific-tag',
  'ef-call-prompt'
  %% with extension mark
}).

-record('PE-OPT-CSIM', {
  'optcsim-header',
  templateID,
  'ef-ssci' = asn1_NOVALUE,
  'ef-fdn' = asn1_NOVALUE,
  'ef-sms' = asn1_NOVALUE,
  'ef-smsp' = asn1_NOVALUE,
  'ef-smss' = asn1_NOVALUE,
  'ef-ssfc' = asn1_NOVALUE,
  'ef-spn' = asn1_NOVALUE,
  'ef-mdn' = asn1_NOVALUE,
  'ef-ecc' = asn1_NOVALUE,
  'ef-me3gpdopc' = asn1_NOVALUE,
  'ef-3gpdopm' = asn1_NOVALUE,
  'ef-sipcap' = asn1_NOVALUE,
  'ef-mipcap' = asn1_NOVALUE,
  'ef-sipupp' = asn1_NOVALUE,
  'ef-mipupp' = asn1_NOVALUE,
  'ef-sipsp' = asn1_NOVALUE,
  'ef-mipsp' = asn1_NOVALUE,
  'ef-sippapss' = asn1_NOVALUE,
  'ef-puzl' = asn1_NOVALUE,
  'ef-maxpuzl' = asn1_NOVALUE,
  'ef-hrpdcap' = asn1_NOVALUE,
  'ef-hrpdupp' = asn1_NOVALUE,
  'ef-csspr' = asn1_NOVALUE,
  'ef-atc' = asn1_NOVALUE,
  'ef-eprl' = asn1_NOVALUE,
  'ef-bcsmscfg' = asn1_NOVALUE,
  'ef-bcsmspref' = asn1_NOVALUE,
  'ef-bcsmstable' = asn1_NOVALUE,
  'ef-bcsmsp' = asn1_NOVALUE,
  'ef-bakpara' = asn1_NOVALUE,
  'ef-upbakpara' = asn1_NOVALUE,
  'ef-mmsn' = asn1_NOVALUE,
  'ef-ext8' = asn1_NOVALUE,
  'ef-mmsicp' = asn1_NOVALUE,
  'ef-mmsup' = asn1_NOVALUE,
  'ef-mmsucp' = asn1_NOVALUE,
  'ef-auth-capability' = asn1_NOVALUE,
  'ef-3gcik' = asn1_NOVALUE,
  'ef-dck' = asn1_NOVALUE,
  'ef-gid1' = asn1_NOVALUE,
  'ef-gid2' = asn1_NOVALUE,
  'ef-cdmacnl' = asn1_NOVALUE,
  'ef-sf-euimid' = asn1_NOVALUE,
  'ef-est' = asn1_NOVALUE,
  'ef-hidden-key' = asn1_NOVALUE,
  'ef-lcsver' = asn1_NOVALUE,
  'ef-lcscp' = asn1_NOVALUE,
  'ef-sdn' = asn1_NOVALUE,
  'ef-ext2' = asn1_NOVALUE,
  'ef-ext3' = asn1_NOVALUE,
  'ef-ici' = asn1_NOVALUE,
  'ef-oci' = asn1_NOVALUE,
  'ef-ext5' = asn1_NOVALUE,
  'ef-ccp2' = asn1_NOVALUE,
  'ef-applabels' = asn1_NOVALUE,
  'ef-model' = asn1_NOVALUE,
  'ef-rc' = asn1_NOVALUE,
  'ef-smscap' = asn1_NOVALUE,
  'ef-mipflags' = asn1_NOVALUE,
  'ef-3gpduppext' = asn1_NOVALUE,
  'ef-ipv6cap' = asn1_NOVALUE,
  'ef-tcpconfig' = asn1_NOVALUE,
  'ef-dgc' = asn1_NOVALUE,
  'ef-wapbrowsercp' = asn1_NOVALUE,
  'ef-wapbrowserbm' = asn1_NOVALUE,
  'ef-mmsconfig' = asn1_NOVALUE,
  'ef-jdl' = asn1_NOVALUE
  %% with extension mark
}).

-record('PE-EAP', {
  'eap-header',
  templateID,
  'df-eap',
  'ef-eapkeys' = asn1_NOVALUE,
  'ef-eapstatus',
  'ef-puid' = asn1_NOVALUE,
  'ef-ps' = asn1_NOVALUE,
  'ef-curid' = asn1_NOVALUE,
  'ef-reid' = asn1_NOVALUE,
  'ef-realm' = asn1_NOVALUE
  %% with extension mark
}).

-record('PE-IoT', {
  'iot-header',
  templateID,
  mf = asn1_NOVALUE,
  'ef-pl' = asn1_NOVALUE,
  'ef-iccid' = asn1_NOVALUE,
  'ef-dir' = asn1_NOVALUE,
  'ef-arr' = asn1_NOVALUE,
  'ef-umpc' = asn1_NOVALUE,
  'adf-usim' = asn1_NOVALUE,
  'ef-imsi',
  'ef-arr-usim' = asn1_NOVALUE,
  'ef-keys' = asn1_NOVALUE,
  'ef-keysPS' = asn1_NOVALUE,
  'ef-hpplmn' = asn1_NOVALUE,
  'ef-ust' = asn1_NOVALUE,
  'ef-start-hfn' = asn1_NOVALUE,
  'ef-threshold' = asn1_NOVALUE,
  'ef-psloci' = asn1_NOVALUE,
  'ef-acc',
  'ef-fplmn' = asn1_NOVALUE,
  'ef-loci' = asn1_NOVALUE,
  'ef-ad' = asn1_NOVALUE,
  'ef-ecc' = asn1_NOVALUE,
  'ef-netpar' = asn1_NOVALUE
  %% with extension mark
}).

-record('PE-OPT-IoT', {
  'optiot-header',
  templateID,
  'ef-fdn' = asn1_NOVALUE,
  'ef-sms' = asn1_NOVALUE,
  'ef-smsp' = asn1_NOVALUE,
  'ef-smss' = asn1_NOVALUE,
  'ef-spn' = asn1_NOVALUE,
  'ef-est' = asn1_NOVALUE,
  'ef-oplmnwact' = asn1_NOVALUE,
  'ef-hplmnwact' = asn1_NOVALUE,
  'ef-ehplmn' = asn1_NOVALUE,
  'ef-epsloci' = asn1_NOVALUE,
  'ef-epsnsc' = asn1_NOVALUE,
  'df-df-5gs' = asn1_NOVALUE,
  'ef-5gs3gpploci' = asn1_NOVALUE,
  'ef-5gsn3gpploci' = asn1_NOVALUE,
  'ef-5gs3gppnsc' = asn1_NOVALUE,
  'ef-5gsn3gppnsc' = asn1_NOVALUE,
  'ef-5gauthkeys' = asn1_NOVALUE,
  'ef-uac-aic' = asn1_NOVALUE,
  'ef-suci-calc-info' = asn1_NOVALUE,
  'ef-opl5g' = asn1_NOVALUE,
  'ef-supi-nai' = asn1_NOVALUE,
  'ef-routing-indicator' = asn1_NOVALUE,
  'ef-ursp' = asn1_NOVALUE,
  'ef-tn3gppsnn' = asn1_NOVALUE,
  'df-df-saip' = asn1_NOVALUE,
  'ef-suci-calc-info-usim' = asn1_NOVALUE
  %% with extension mark
}).

-record('PE-GenericFileManagement', {
  'gfm-header',
  fileManagementCMD
  %% with extension mark
}).

-record('MappingParameter', {
  mappingOptions,
  mappingSource
  %% with extension mark
}).

-record('AlgoParameter', {
  algorithmID,
  algorithmOptions,
  key,
  opc,
  rotationConstants = asn1_DEFAULT,
  xoringConstants = asn1_DEFAULT,
  authCounterMax = asn1_NOVALUE,
  numberOfKeccak = asn1_DEFAULT
  %% with extension mark
}).

-record('PE-AKAParameter', {
  'aka-header',
  algoConfiguration,
  sqnOptions = asn1_DEFAULT,
  sqnDelta = asn1_DEFAULT,
  sqnAgeLimit = asn1_DEFAULT,
  sqnInit = asn1_DEFAULT
  %% with extension mark
}).

-record('PE-CDMAParameter', {
  'cdma-header',
  authenticationKey,
  ssd = asn1_NOVALUE,
  hrpdAccessAuthenticationData = asn1_NOVALUE,
  simpleIPAuthenticationData = asn1_NOVALUE,
  mobileIPAuthenticationData = asn1_NOVALUE
  %% with extension mark
}).

-record('PINConfiguration', {
  keyReference,
  pinValue,
  unblockingPINReference = asn1_NOVALUE,
  pinAttributes = asn1_DEFAULT,
  'maxNumOfAttemps-retryNumLeft' = asn1_DEFAULT
  %% with extension mark
}).

-record('PE-PINCodes', {
  'pin-Header',
  pinCodes
  %% with extension mark
}).

-record('PUKConfiguration', {
  keyReference,
  pukValue,
  'maxNumOfAttemps-retryNumLeft' = asn1_DEFAULT
  %% with extension mark
}).

-record('PE-PUKCodes', {
  'puk-Header',
  pukCodes
  %% with extension mark
}).

-record('PE-SecurityDomain', {
  'sd-Header',
  instance,
  keyList = asn1_NOVALUE,
  sdPersoData = asn1_NOVALUE,
  openPersoData = asn1_NOVALUE,
  catTpParameters = asn1_NOVALUE
  %% with extension mark
}).

-record('PE-SecurityDomain_openPersoData', {
  restrictParameter = asn1_NOVALUE,
  contactlessProtocolParameters = asn1_NOVALUE
  %% with extension mark
}).

-record('PE-SecurityDomain_catTpParameters', {
  catTpMaxSduSize,
  catTpMaxPduSize
  %% with extension mark
}).

-record('KeyObject', {
  keyUsageQualifier,
  keyAccess = asn1_DEFAULT,
  keyIdentifier,
  keyVersionNumber,
  keyCounterValue = asn1_NOVALUE,
  keyCompontents
  %% with extension mark
}).

-record('KeyObject_keyCompontents_SEQOF', {
  keyType,
  keyData,
  macLength = asn1_DEFAULT
  %% with extension mark
}).

-record('PE-Application', {
  'app-Header',
  loadBlock = asn1_NOVALUE,
  instanceList = asn1_NOVALUE
  %% with extension mark
}).

-record('ApplicationLoadPackage', {
  loadPackageAID,
  securityDomainAID = asn1_NOVALUE,
  nonVolatileCodeLimitC6 = asn1_NOVALUE,
  volatileDataLimitC7 = asn1_NOVALUE,
  nonVolatileDataLimitC8 = asn1_NOVALUE,
  hashValue = asn1_NOVALUE,
  loadBlockObject
  %% with extension mark
}).

-record('ApplicationInstance', {
  applicationLoadPackageAID,
  classAID,
  instanceAID,
  extraditeSecurityDomainAID = asn1_NOVALUE,
  applicationPrivileges,
  lifeCycleState = asn1_DEFAULT,
  applicationSpecificParametersC9,
  systemSpecificParameters = asn1_NOVALUE,
  applicationParameters = asn1_NOVALUE,
  processData = asn1_NOVALUE,
  controlReferenceTemplate = asn1_NOVALUE
  %% with extension mark
}).

-record('ApplicationSystemParameters', {
  volatileMemoryQuotaC7 = asn1_NOVALUE,
  nonVolatileMemoryQuotaC8 = asn1_NOVALUE,
  globalServiceParameters = asn1_NOVALUE,
  implicitSelectionParameter = asn1_NOVALUE,
  volatileReservedMemory = asn1_NOVALUE,
  nonVolatileReservedMemory = asn1_NOVALUE,
  ts102226SIMFileAccessToolkitParameter = asn1_NOVALUE,
  ts102226AdditionalContactlessParameters = asn1_NOVALUE,
  contactlessProtocolParameters = asn1_NOVALUE,
  userInteractionContactlessParameters = asn1_NOVALUE,
  cumulativeGrantedVolatileMemory = asn1_NOVALUE,
  cumulativeGrantedNonVolatileMemory = asn1_NOVALUE
  %% with extension mark
}).

-record('UICCApplicationParameters', {
  uiccToolkitApplicationSpecificParametersField = asn1_NOVALUE,
  uiccAccessApplicationSpecificParametersField = asn1_NOVALUE,
  uiccAdministrativeAccessApplicationSpecificParametersField = asn1_NOVALUE
  %% with extension mark
}).

-record('TS102226AdditionalContactlessParameters', {
  protocolParameterData
  %% with extension mark
}).

-record('ControlReferenceTemplate', {
  applicationProviderIdentifier
  %% with extension mark
}).

-record('PE-RFM', {
  'rfm-header',
  instanceAID,
  securityDomainAID = asn1_NOVALUE,
  tarList = asn1_NOVALUE,
  minimumSecurityLevel,
  uiccAccessDomain,
  uiccAdminAccessDomain,
  adfRFMAccess = asn1_NOVALUE
  %% with extension mark
}).

-record('ADFRFMAccess', {
  adfAID,
  adfAccessDomain,
  adfAdminAccessDomain
  %% with extension mark
}).

-record('PE-NonStandard', {
  'nonStandard-header',
  issuerID,
  content
  %% with extension mark
}).

-record('PE-End', {
  'end-header'
  %% with extension mark
}).

-record('PEStatus', {
  status,
  identification = asn1_NOVALUE,
  'additional-information' = asn1_NOVALUE,
  offset = asn1_NOVALUE
  %% with extension mark
}).

-record('EUICCResponse', {
  peStatus,
  profileInstallationAborted = asn1_NOVALUE,
  statusMessage = asn1_NOVALUE
  %% with extension mark
}).

-define('maxUInt8', 255).
-define('maxUInt15', 32767).
-define('maxUInt16', 65535).
-define('maxUInt31', 2147483647).
-endif. %% _PROFILE_HRL_
