%% Compiled ASN.1 Profile - Sample User Authentication Schema
%% Generated by Erlang ASN.1 compiler

-module('UserAuthProfile').
-export([encode/2, decode/2]).

%% Record definitions

-record('UserRecord', {
    userId :: integer(),
    userName :: binary(),
    userEmail :: binary(),
    accountType :: integer(),
    isActive = true :: boolean(),
    createdDate :: binary(),
    lastLogin :: binary() | undefined
}).

-record('SessionInfo', {
    sessionId :: binary(),
    startTime :: binary(),
    expiryTime :: binary(),
    deviceInfo :: binary() | undefined
}).

-record('Credentials', {
    passwordHash :: binary(),
    salt :: binary(),
    algorithm = 'sha256' :: atom(),
    iterations = 10000 :: integer()
}).

-record('ProfileData', {
    firstName :: binary(),
    lastName :: binary(),
    phoneNumber :: binary() | undefined,
    address :: binary() | undefined
}).

%% Type specifications for ASN.1 encoding

encode('UserRecord', UserRecord) ->
    asn1rt_nif:encode_per_complete([
        {1, UserRecord#'UserRecord'.userId},
        {2, UserRecord#'UserRecord'.userName},
        {3, UserRecord#'UserRecord'.userEmail},
        {4, UserRecord#'UserRecord'.accountType},
        {5, UserRecord#'UserRecord'.isActive},
        {6, UserRecord#'UserRecord'.createdDate},
        {7, UserRecord#'UserRecord'.lastLogin}
    ]).

%% Additional type information from ASN.1 schema
%% UserRecord ::= SEQUENCE {
%%     userId [0] INTEGER,
%%     userName [1] UTF8String (SIZE(1..100)),
%%     userEmail [2] IA5String (SIZE(1..255)),
%%     accountType [3] INTEGER (0..3),
%%     isActive [4] BOOLEAN DEFAULT TRUE,
%%     createdDate [5] UTCTime,
%%     lastLogin [6] UTCTime OPTIONAL
%% }

%% SessionInfo ::= SEQUENCE {
%%     sessionId [0] OCTET STRING (SIZE(16)),
%%     startTime [1] UTCTime,
%%     expiryTime [2] UTCTime,
%%     deviceInfo [3] UTF8String OPTIONAL
%% }

%% Credentials ::= SEQUENCE {
%%     passwordHash [0] OCTET STRING (SIZE(32..64)),
%%     salt [1] OCTET STRING (SIZE(16)),
%%     algorithm [2] ENUMERATED {md5(0), sha1(1), sha256(2)},
%%     iterations [3] INTEGER (1000..1000000)
%% }

%% ProfileData ::= SEQUENCE {
%%     firstName [0] UTF8String (SIZE(1..50)),
%%     lastName [1] UTF8String (SIZE(1..50)),
%%     phoneNumber [2] UTF8String OPTIONAL,
%%     address [3] UTF8String OPTIONAL
%% }
